export default {
  "index": "Overview",
  "availability": "Availability",
  "scalability": "Scalability",
  "reliability": "Reliability",
  "fault-tolerance": "Fault Tolerance",
  "load-balancing": "Load Balancing",
  "replication": "Replication",
  "partitioning": "Partitioning",
  "sharding": "Sharding",
  "transactions": "Transactions",
  "indexing": "Indexing",
  "sql": "SQL",
  "nosql": "NoSQL",
  "cache-invalidation": "Cache Invalidation",
  "kafka": "Kafka",
  "rabbitmq": "RabbitMQ",
  "sqs": "SQS",
  "event-driven-architecture": "Event-Driven Architecture",
  "api-gateway": "API Gateway",
  "service-discovery": "Service Discovery",
  "circuit-breaker": "Circuit Breaker",
  "retry": "Retry",
  "saga-pattern": "Saga Pattern",
  "cqrs": "CQRS",
  "event-sourcing": "Event Sourcing",
  "service-mesh": "Service Mesh",
  "observability": "Observability",
  "distributed-tracing": "Distributed Tracing",
  "leader-election": "Leader Election",
  "consensus": "Consensus",
  "raft": "Raft",
  "paxos": "Paxos",
  "gossip-protocol": "Gossip Protocol",
  "cap-theorem": "CAP Theorem",
  "caching": "Caching Strategies",
  "consistency-models": "Consistency Models"
};
